sonar.projectKey=imamabidin69-svg_SmartTriageAI
sonar.organization=imamabidin69-svg

sonar.projectName=SmartTriage AI
sonar.sources=app,components,lib,hooks
sonar.exclusions=**/node_modules/**,**/.next/**,**/*.test.ts,**/*.test.tsx

sonar.sourceEncoding=UTF-8
